version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: compassuser
      POSTGRES_PASSWORD: compasspass
      POSTGRES_DB: compasscar_db
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - compass_network

volumes:
  pgdata:

networks:
  compass_network: